### ISSUE TITLE
Contributing oculus code to three.js?

### ISSUE THREAD

**Issue by mrdoob** [troffmo5/voxel-oculus#1]
Lovely stuff!

Would you be up for contributing the Oculus code to three.js?

We already have some other modes in there already:
https://github.com/mrdoob/three.js/tree/master/examples/js/effects

`Effect` may not be the best name, maybe I should rename those to `*RenderModes` or something like that...

**Comment by troffmo5** [comment]
Yes, i have already wrote an "Effect" for this demo http://oculusstreetview.eu.pn/
As you can see from the sources i called it OculusEffect.js.
I tested it only with my own DIY HMD, that uses the same technology of the Oculus Rift but different components (e.g. lenses and display). You can see some videos of it here http://www.youtube.com/watch?v=n-sW-ElV3n0 and here http://www.youtube.com/watch?v=dm3NMQYTIhc.
I'm not really sure if the distortion and its parameters are working good on the Oculus, i'm still waiting for it, but if you like i can add it anyway and eventually update it.

I could change the name Oculus with something else to indicate that it is compatible with other HMDs

**Comment by mrdoob** [comment]
Ah, I see.
Up to you. I guess it could be OculusRiftEffect.js and then fix it whenever it can be properly tested.
